#!/usr/bin/env python3

from datetime import date, timedelta
from argparse import ArgumentParser


def parse_args():
    argp = ArgumentParser(description=__doc__)
    argp.add_argument("--year", required=True, default=2020, type=int,
                      help="Year")
    return argp.parse_args()


def all_sundays(year):
    date_point = date(year, 1, 1)
    date_point += timedelta(days=6 - date_point.weekday())
    while date_point.year == year:
        yield date_point
        date_point += timedelta(days=7)


if __name__ == "__main__":
    args = parse_args()
    for s in all_sundays(args.year):
        print(s)
