#!/bin/bash

# Setup for Angular development.

# Configure Linux to support ng serve automatic reload
# https://stackoverflow.com/questions/48092880/ng-serve-not-detecting-file-changes-automatically
echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system
