#!/bin/bash -e

deb_installed() {
    if dpkg -s "$1" 2>/dev/null >/dev/null; then
        return 0
    else
        return 1
    fi
}

dnf_installed() {
    if dnf list installed | grep "$1" 2>/dev/null >/dev/null; then
        return 0
    else
        return 1
    fi
}

bin_installed() {
    if command -v "$1" 2>/dev/null >/dev/null; then
        return 0
    else
        return 1
    fi
}

brew_installed() {
    # brew info {{formula}}
    if brew ls --versions "$1" 2>/dev/null >/dev/null; then
        return 0
    else
        return 1
    fi
}
