#!/bin/bash

set -Eeuo pipefail

function print_help () {
    echo "Usage: $(basename -- "$0") (file1.pdf [file2.pdf ...] | *.pdf)"
    exit 1
}

if [ "$#" -lt "1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    print_help
fi

pdftk "$@" cat output output.pdf
