#!/bin/bash

set -Eeuo pipefail

function print_help () {
    echo "Usage: $(basename -- "$0") input_file.pdf output_directory"
    exit 1
}

if [ "$#" -ne "2" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    print_help
fi

mkdir -p "$2"

pdftk "$1" burst output "$2"/%d.pdf
