#!/bin/bash

case $1 in
    caps)
        setxkbmap -option caps:swapescape
        shift
    ;;
    audio)
        pulseaudio -k && sudo alsa force-reload
        shift
    ;;
    repeat-key)
        xset r on
    ;;
    *)
        echo "Unknown!"
        exit 1
    ;;
esac
