#!/bin/bash

# https://askubuntu.com/questions/1175987/how-to-change-the-background-to-use-built-in-theme-from-gnome-terminal-profile-p
# https://help.gnome.org/users/gnome-terminal/stable/app-colors.html.en
# https://developer.gnome.org/gio/stable/gsettings-tool.html

# Gnome 3 can be customised from the command line via the gsettings command.

# # The following lines should help you to find what you're looking for by
# # listing the ranges for all keys for each schema.
# for schema in $(gsettings list-schemas | sort); do
#    for key in $(gsettings list-keys $schema | sort); do
#        value="$(gsettings range $schema $key | tr "\n" " ")"
#        echo "$schema :: $key :: $value"
#    done
# done

profile_id="b1dcc9dd-5262-4d8d-a863-c897e6d979b9"

function light {
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile_id}/ foreground-color 'rgb(101,123,131)'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile_id}/ background-color 'rgb(253,246,227)'
}

function dark {
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile_id}/ foreground-color 'rgb(131,148,150)'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile_id}/ background-color 'rgb(0,43,54)'
}

case $1 in
    light)
    light
    ;;
    dark)
    dark
    ;;
esac
